Login
may-den/parking-system pull request #1
Opened 2016-11-15 14:34 UTC by benmorrismayden

2016-11-15 15:54 UTC, aimeeew requested changes

2016-11-15 15:54 UTC, aimee-wyld commented on classes/DbConnector.php
> +        $servername = "192.168.20.56";
Single quotes?

2016-11-15 15:54 UTC, aimee-wyld commented on classes/DbConnector.php
> +        $servername = "192.168.20.56";
(and four more below)

2016-11-15 15:54 UTC, aimee-wyld commented on classes/User.php
> +        $sql = "SELECT * FROM `users` WHERE `email` = :email;";
Double quotes: 31, 37, 40, 43, 44, 66, 82

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +            'password' => sha1("1" . 'aaa')
double quotes line 17 and 60

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +            'password' => sha1("1" . 'aaa')
& 41

2016-11-15 15:54 UTC, aimee-wyld commented on classes/DbConnector.php
> +    public function __construct()
Needs docblocking

2016-11-15 15:54 UTC, aimee-wyld commented on classes/DbConnector.php
> +    public function getDB(){
needs docblocking

2016-11-15 15:54 UTC, aimee-wyld commented on classes/User.php
> +    public function logOut(){
needs docblocking

2016-11-15 15:54 UTC, aimee-wyld commented on classes/User.php
> +    public function getLoggedIn(){
needs docblocking

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +    public function testSuccessfulLogin() {
docblocks

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +    public function testNonExistantUserLogin() {
docblocks

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +    public function testIncorrectPasswordLogin() {
docblocks

2016-11-15 15:54 UTC, aimee-wyld commented on test/classes/UserTest.php
> +    public function testLogOut() {
docblocks

2016-11-15 17:38 UTC, ross-eastman-mayden commented on test/classes/UserTest.php
> +require '/Users/benmorris/Documents/Development/academy/parking-system/classes/User.php';
Absolute filepath - absolutely no no

2016-11-15 18:53 UTC, ross-eastman-mayden commented on test/classes/UserTest.php
> +require '/Users/benmorris/Documents/Development/academy/parking-system/classes/User.php';
actually, if you're autoloading, why require the class?

2016-11-16 10:45 UTC, JessI23 commented on login.html
> +            <form method="post" action="emailpasstet.php" id="loginForm" class="form-horizontal">
id/class name loginForm inconsistent with using - instead of cammelCase

2016-11-16 18:12 UTC, ross-eastman-mayden commented on index.php
> +}else {
Dodge formatting

2016-11-16 18:13 UTC, ross-eastman-mayden commented on test/classes/UserTest.php
> +require __DIR__ . '/../../classes/User.php';
This should work without explicitly requiring the class(as that's the autoloaders job)

2016-11-18 13:48 UTC, merged