Display spaces
may-den/parking-system pull request #2
Opened 2016-11-15 14:34 UTC by benmorrismayden

2016-11-15 17:39 UTC, ross-eastman-mayden commented on test/classes/CarparkTest.php
> +require '/Users/benmorris/Documents/Development/academy/parking-system/classes/Carpark.php';
absolute file paths again

2016-11-16 10:26 UTC, ralph-rutter requested changes

2016-11-16 10:26 UTC, ralph-rutter commented on classes/Carpark.php
> + */
We don't need the auto-generated comments.

2016-11-16 10:26 UTC, ralph-rutter commented on classes/Carpark.php
> +        $statement = $pdo->query('SELECT * FROM `' . self::CARPARK_TABLE_NAME . '` WHERE `name` = \'' . $name . '\';');
This query call needs splitting out into prepare and execute, to avoid sql injection vulnerability.

2016-11-16 10:26 UTC, ralph-rutter commented on classes/Carpark.php
> +        $result = $statement->fetch();
Passing fetch PDO::FETCH_ASSOC will return just the associative array and not both assoc. and indexed, hence storing less data.

2016-11-16 10:26 UTC, ralph-rutter commented on autoload.php
> +function class_autoloader($class) {
Needs a docBlock

2016-11-16 10:26 UTC, ralph-rutter commented on classes/Carpark.php
> +    public function __construct(PDO $pdo, $name) {
needs a DocBlock

2016-11-16 10:26 UTC, ralph-rutter commented on classes/Carpark.php
> +    public function getId() {
These getters need docBlocks. Also should isVisitor() be getIsVisitor() for consistency?

2016-11-16 10:26 UTC, ralph-rutter commented on js/calendar.js
> +$toStartDate = $date
Do you need this variable? It seems only to appear again in line 20, where it still is the same as $date.

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> + */
Don't need automated comments

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> +require '/Users/benmorris/Documents/Development/academy/parking-system/vendor/autoload.php';
These probably need to be relative paths, so that they'll work for other users.

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> + */
Don't need this comment.

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> +
In order to fetch, the prepared statement needs to be executed after having been prepared, so I would imagine the execute method on $mockStatement will needs to appear somewhere in the test.

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> +        $mockPDO->method('prepare')->willReturn($mockStatement);
The same applies here with the execute method.

2016-11-16 10:26 UTC, ralph-rutter commented on test/classes/CarparkTest.php
> +        }
This test needs some assertions.

2016-11-18 13:25 UTC, mporam approved these changes

2016-11-18 13:25 UTC, merged